### ISSUE TITLE
plugin doesn't work with logstash >= 5

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-codec-csv#1]
the plugin still locks the dependency on logstash-core-plugin-api at ~> 1, it needs a [change like the one performed in the supported plugins](https://github.com/logstash-plugins/logstash-filter-date/commit/0e9649b8b643bf03f83d8106021c59e5f4279ae0)

**Comment by colinsurprenant** [comment]
#4 to the rescue
