### ISSUE TITLE
How to install   logstash-codec-csv on logstash when there is no internet connection

### ISSUE THREAD

**Issue by daliangzao-ayuan** [logstash-plugins/logstash-codec-csv#10]
Hello, I have a problem, there is no internet connection,  I was  installed the logstash ,  
How to install  the plugin on Logstash with CentOS7 system.
If you have a solution, please let me know. Thanks

**Comment by mashhurs** [comment]
You need to download (got to [rubygem](https://rubygems.org/gems/logstash-codec-csv) and download), copy the gem to your CentOS7 machine and use `bin/logstash-plugin install /path/to/logstash-codec-csv-{version}.gem` command to install it.
Github is managing issues/bugs and requesting enhancement. For this kind of discussions, please use https://discuss.elastic.co/
